config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :issuances
  resources :accesses
  resources :attendances
  resources :leaves
  root 'attendances#index'

  resources :equipment do
    resources :issuances
  end

  resources :accesses do
    resources :issuances
  end

  devise_for :users, :controllers => { registrations: 'registrations' } do
    member do
      get :managers, :employees
    end
  end

  resources :products, only: [:index]
  # resources :roles,  only: [:create, :destroy]
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  has_many :issuances, as: :issuable
  has_many :users, through: :issuances, source: :user

  validates :name, presence:true
  validates :description, presence:true
  
  enum kind: [:electronics, :stationary ]
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
    before_action :authenticate_user!
    before_action :find_equipment, only: [:show, :edit, :update, :destroy]

    def index
      @equipment = Equipment.all
    end

    def new
      @equipment = Equipment.new
    end

    def create
      @equipment = Equipment.create(equipment_params)
      if @equipment.save
        flash[:success]= "Equipment Created Successfully"
        redirect_to @equipment
      else
        flash[:danger]= "Equipment not created, contains errors"
        render 'new'
      end
    end

    def edit
      @equipment = Equipment.find(params[:id])
    end

    def update
      @equipment.update(equipment_params)
      if @equipment.save
        flash[:success]= "Equipment updated Successfully"
        redirect_to @equipment
      else
        flash[:danger]= "Equipment not updated"
        render 'new'
      end
    end

    def destroy
      @equipment.destroy
      redirect_to equipment_index_path
      flash[:danger]= "Equipment Deleted"

    end

    private

    def find_equipment
      @equipment = Equipment.find(params[:id])
    end

    def equipment_params
      params.require(:equipment).permit(:name, :description, :kind)
    end
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/views/equipment/_equipment.html.erb
<table>
	<thead>
	  <tr>
	    <th> Name </th>
	    <th> Description </th>
	    <th> Type </th>
    <th> Actions </th>
	  </tr>
	</thead>
	<tbody>
		<% @equipment.each do |equipment| %>
			<tr>
				<td><%= equipment.name.capitalize %></td>
				<td><%= equipment.description.capitalize %></td>
				<td><%= equipment.kind.capitalize %></td>
				<td><%= link_to "Edit", edit_equipment_path(equipment) %> |
	     			<%= link_to "Delete", equipment_path(equipment), method: :delete %></td>
			</tr>
		<% end %>

	</tbody>
</table>

app/views/equipment/_form.html.erb
<div class = "panel">
	<h3> Add an Equipment </h3>
	<%= form_for @equipment do |f| %>
	  <%= f.label :name %>
	  <%= f.text_field :name,  class: 'form-control', placeholder: 'Enter Name', cached: true  %>

	  <%= f.label :description %>
    <%= f.text_field :description,  class: 'form-control', placeholder: 'Enter Description', cached: true %>

    <%= f.label :Select_Equipment_type %>
    <%= f.select :kind, Equipment.kinds.keys.map { |k| [k.humanize, k] }%>

		<%= f.submit 'Submit', class: "button success small" %>
	<% end %>
</div>

app/views/equipment/edit.html.erb
<% provide(:title,"New Equipment") %>
	<%= render 'form' %>

app/views/equipment/index.html.erb
<% provide(:title, "Leaves") %>
<div class="panel" align="center">
	<h1> Equipment </h1>
	<br>

	<% if @equipment.any? %>
		<%= render 'equipment' %>
	<% end %>
</div>

app/views/equipment/new.html.erb
<% provide(:title,"New Equipment") %>
	<%= render 'form' %>

app/views/equipment/show.html.erb
<% provide(:title, "Equipment") %>
<div align="center">
	<h3> Equipment </h3>
	<table>
		<thead>
		  <tr>
		    <th> Name </th>
		    <th> Description </th>
		    <th> Type </th>
        <th> Actions </th>
		  </tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @equipment.name.capitalize %></td>
				<td><%= @equipment.description.capitalize %></td>
				<td><%= @equipment.kind.capitalize %></td>
				<td><%= link_to "Edit", edit_equipment_path(@equipment) %> |
         <%= link_to "Delete", equipment_path(@equipment), method: :delete %></td>
			</tr>
		</tbody>
	</table>
</div>