config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :issuances
  resources :accesses
  resources :attendances
  resources :leaves
  root 'attendances#index'

  resources :equipment do
    resources :issuances
  end

  resources :accesses do
    resources :issuances
  end

  devise_for :users, :controllers => { registrations: 'registrations' } do
    member do
      get :managers, :employees
    end
  end

  resources :products, only: [:index]
  # resources :roles,  only: [:create, :destroy]
end

app/models/leave.rb
class Leave < ApplicationRecord
  belongs_to :user

  enum state: [:approved, :rejected, :open, :revoked]
  enum kind: [:sick, :annual, :restricted, :unpaid ]

  validates :message, presence:true
  validates :to_date, presence:true
  validates :from_date, presence:true

  def start_time
    self.from
  end

  def end_time
    self.to
  end

  def correct_leave
    DateTime.parse(to).mjd >= DateTime.parse(from).mjd
  end

  def from
    from_date.strftime("%d-%m-%Y")
  end

  def to
    to_date.strftime("%d-%m-%Y")
  end

  def days
    ((from_date.to_date..to_date.to_date).collect(&:wday) - [0, 6]).count
  end
end

app/controllers/leaves_controller.rb
class LeavesController < ApplicationController
	before_action :authenticate_user!
	before_action :find_leave, only: [:show, :update, :edit, :destroy]

	def new
		@leave = Leave.new
	end
	def index
		@leaves = if params[:manager]
								current_user.employees.map(&:leaves).flatten
							else
			 					current_user.leaves.order(created_at: :desc)
							end
	end

	def create
		@leave = current_user.leaves.new(leave_params)
		if @leave.correct_leave
			@leave.save
			flash[:success] = 'Leave has been successfully requested.'
			redirect_to :leaves
		else
			flash[:error] = 'Leave dates incorrect.'
			render 'new'
		end
	end

	def update
		if action? :approve
			@leave.approved!
			flash[:alert] = 'Leave request Approved!'
			redirect_to :back
		elsif action? :reject
			@leave.rejected!
			flash[:alert] = 'Leave request Rejected!'
			redirect_to :back
		else
			@leave.update(leave_params)
			flash[:alert] = 'Leave successfully edited !'
			redirect_to :leaves
		end
	end

	def destroy
		@leave.destroy
		redirect_to :leaves, notice: 'Leave was successfully cancelled.'
	end

	private

	def action?(act)
    params['commit'].casecmp(act.to_s.downcase).zero?
  end

	def find_leave
		@leave = Leave.find(params[:id])
	end

	def leave_params
		params.require(:leave).permit(:message, :from_date, :to_date, :status, :kind)
	end
end

app/helpers/leaves_helper.rb
module LeavesHelper
end

app/views/leaves/_form.html.erb
<div class = "panel">
	<h1> Apply For a leave </h1>
	<%= form_for @leave do |f| %>
	  <%= f.label :from %>
	  <%= f.date_field :from_date, class: 'form-control', placeholder: 'Select From Date' %>

	  <%= f.label :to %>
	  <%= f.date_field :to_date,  class: 'form-control', placeholder: 'Select To Date' %>

	  <%= f.label :message %>
	  <%= f.text_field :message, class: 'form-control' ,placeholder: 'Enter Message' %>

		<%= f.label :Select_Leave_type %>
	  <%= f.select :kind, Leave.kinds.keys.map { |k| [k.humanize, k] }%>

		<%= f.submit 'Apply', class: "button success small" %>
	<% end %>
</div>

app/views/leaves/_leave.html.erb
<table align="center">
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Days</th>
      <th>Kind</th>
      <th>Reason</th>
      <th>Status</th>
      <th>Manager's Name</th>
      <% if (@leaves.first.user != current_user) && current_user.manager? %>
        <th>Manager actions</th>
      <% else %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @leaves.each do |leave| %>
      <tr>
        <td><%= leave.user.full_name.capitalize %></td>
        <td><%= leave.from %></td>
        <td><%= leave.to %></td>
        <td><%= leave.days %></td>
        <td><%= leave.kind.capitalize %></td>
        <td><%= leave.message %></td>
        <td><%= leave.state.capitalize %></td>
        <td><%= leave.user.managers&.first&.full_name %></td>
        <% if (leave.user != current_user) && current_user.manager? %>
          <td>
            <%= form_for leave do |f|%>
              <% if leave.approved? %>
                <%= f.submit "Reject" , class: "button tiny alert round" %>
              <% elsif leave.rejected?%>
                <%= f.submit "Approve", class: "button tiny success round" %>
              <% else %>
                <%= f.submit "Approve", class: "button tiny success round" %>
                <%= f.submit "Reject" , class: "button tiny alert round" %>
              <% end %>
            <% end %>
          </td>
        <% else %>
          <td><%= link_to "View", leave_path(leave) , class: "button tiny success round"%>
          <%= link_to "Edit", edit_leave_path(leave) , class: "button tiny round"%>
           <%= link_to "Revoke", leave_path(leave), method: :delete, class: "button tiny alert round" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/leaves/edit.html.erb
<%= provide(:title, "Edit Leave") %>
<%= render 'leaves/form' %>

app/views/leaves/index.html.erb
<% provide(:title, "Leaves") %>
<div class="panel" align="center">
	<h1> LEAVES </h1>
	<br>

<% if  current_user.employee? %>
	<%= link_to "Apply", new_leave_path, class: "button round tiny" %>
<% end %>
<% if @leaves.any? %>
	<%= render 'leave' %>
<% end %>
<%= month_calendar events: Leave.all do |date, leaves| %>
  <%= date %>

  <% leaves.each  do |leave| %>
    <div>
	    <% if leave.state == 'approved'  %>
	       <b>On Leave</b> (<%= leave.user.first_name.capitalize %>)
	    <% end %>
    </div>
 <% end %>
<% end %>
</div>

app/views/leaves/new.html.erb
<%= provide(:title , "New Leave" ) %>
<%= render 'leaves/form' %>

app/views/leaves/show.html.erb
<% provide(:title, "Leave") %>
<div align="center">
	<h1> Leave </h1>
	<table>
		<thead>
		  <tr>
		    <th> From </th>
		    <th> To </th>
		    <th> Days </th>
		    <th> Message </th>
		    <th>Status </th>
		    <th> Actions </th>
		  </tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @leave.from %></td>
				<td><%= @leave.to %></td>
				<td><%= @leave.days %></td>
				<td><%= @leave.message %></td>
				<td><%= @leave.state %></td>
				<td><%= link_to "Edit", edit_leave_path(@leave) %> | 
         <%= link_to "Cancel", leave_path(@leave), method: :delete %></td>
			</tr>
		</tbody>
	</table>
</div>