config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :issuances
  resources :accesses
  resources :attendances
  resources :leaves
  root 'attendances#index'

  resources :equipment do
    resources :issuances
  end

  resources :accesses do
    resources :issuances
  end

  devise_for :users, :controllers => { registrations: 'registrations' } do
    member do
      get :managers, :employees
    end
  end

  resources :products, only: [:index]
  # resources :roles,  only: [:create, :destroy]
end

app/models/issuance.rb
class Issuance < ApplicationRecord
  belongs_to :issuer, class_name: 'User', required: false
  belongs_to :issuable, polymorphic: true
  belongs_to :user

  validates :description, presence: true

  enum state: [:open, :approved, :rejected, :revoked]
end

app/controllers/issuances_controller.rb
class IssuancesController < ApplicationController
  before_action :find_issuable, only: :create

  def show
    @equipment = Equipment.find(params[:equipment_id]) if params[:equipment_id]
    @access = Access.find(params[:access_id]) if params[:access_id]
    @issuance = Issuance.find(params[:id])
  end
  def index
    @leaves = if params[:manager]
                current_user.employees.map(&:leaves).flatten
              else
                current_user.leaves.order(created_at: :desc)
              end
    @issuances = if params[:manager]
                  current_user.employees.map(&:issuances).flatten
                 else
                  current_user.issuances.order(created_at: :desc)
                 end
  end

  def create
    @issuance = current_user.issuances.build(issuable: @issuable, description: params[:issuance][:description])
    if @issuance.save
      redirect_to equipment_issuance_path(@issuable.id, @issuance)
      flash[:success] = "Request created successfully"
    else
      redirect_to :back
      flash[:alert] = "Request not Created"
    end
  end

  def edit
    @issuance = Issuance.find(params[:id])
  end

  def update
    @issuance = Issuance.find(params[:id])
		if action? :approve
			@issuance.approved!
			flash[:alert] = 'Issuance request Approved!'
      @issuance.update_attributes(issuer_id: current_user.id)
			redirect_to :back
		elsif action? :reject
			@issuance.rejected!
      @issuance.update_attributes(issuer_id: current_user.id)
			flash[:alert] = 'Issuance request Rejected!'
			redirect_to :back
		else
			@issuance.update(leave_params)
			flash[:alert] = 'Issuance successfully edited !'
      redirect_to :back
		end
    flash[:alert] = 'Issuance successfully edited !'
	end

  private

  def find_issuable
    unless params[:equipment][:id].empty?
      @issuable = Equipment.find(params[:equipment][:id]) if params[:equipment] && params[:equipment][:id]
    end
    @issuable = Access.find(params[:access][:id]) if params[:access] && params[:access][:id]
  end

  def action?(act)
    params['commit'].casecmp(act.to_s.downcase).zero?
  end

end

app/helpers/issuances_helper.rb
module IssuancesHelper
end

app/views/issuances/_form.html.erb
<div class = "panel">
	<h3> Request for an Equipment </h3>
	<%= form_for Issuance.new do |f| %>
	  <%= f.label :name %>
	  <%= select("equipment","id", Equipment.all.map{ |e| [e.name, e.id]}, {prompt: 'Select Equipment Name'}) %>

		<%= f.label :description %>
    <%= f.text_field :description,  class: 'form-control', placeholder: 'Enter Description', cached: true %>

    <%= f.label :Select_Equipment_type %>
    <%= select 'equipment',  'kind', Equipment.kinds.keys.map { |k| [k.humanize, k] }%>

		<%= f.submit 'Submit', class: "button success small" %>
	<% end %>
</div>

app/views/issuances/_issuance_access.html.erb
<% provide(:title,"All Requests")%>
<table>
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Request for</th>
      <th>Access Name</th>
      <th>Access URL</th>
      <th>Access Type</th>
      <th>Requested On</th>
      <th>Manager's Name</th>
      <th>Status</th>
      <% if (@issuances.first.user != current_user) && current_user.manager? %>
        <th>Manager actions</th>
      <% else %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @issuances.each do |issuance|%>
      <tr>
      <% if issuance.issuable_type == 'Access'%>
        <td><%= issuance.user.full_name.capitalize %></td>
        <td><%= issuance.issuable_type %></td>
        <td><%= issuance.issuable.name.capitalize %></td>
        <td><%= issuance.issuable.url %></td>
        <td><%= issuance.issuable.kind.capitalize %></td>
        <td><%= issuance.created_at.strftime("%D") %></td>
        <td><%= issuance&.issuer&.full_name %></td>
        <td><%= issuance.state %></td>
        <% if (issuance.user != current_user) && current_user.manager? %>
          <td>
            <%= form_for issuance do |f|%>
              <% if issuance.approved? %>
                <%= f.submit "Reject" , class: "button tiny alert round" %>
              <% elsif issuance.rejected?%>
                <%= f.submit "Approve", class: "button tiny success round" %>
              <% else %>
                <%= f.submit "Approve", class: "button tiny success round" %>
                <%= f.submit "Reject" , class: "button tiny alert round" %>
              <% end %>
            <% end %>
          </td>
        <% else %>
          <td><%= link_to "View", issuance_path(issuance) , class: "button tiny success round"%>
          <%= link_to "Edit", edit_access_path(issuance.issuable.id) , class: "button tiny round"%>
           <%= link_to "Revoke", issuance_path(issuance), method: :delete, class: "button tiny alert round" %></td>
        <% end %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/issuances/_issuance_equipment.html.erb
<% provide(:title,"All Requests")%>
<table>
  <thead>
    <tr>
      <th>Employee Name</th>
      <th>Request for</th>
      <th>Equipment Name</th>
      <th>Equipment Requested For</th>
      <th>Equipment Type</th>
      <th>Requested On</th>
      <th>Manager's Name</th>
      <th>Status</th>
      <% if (@issuances.first.user != current_user) && current_user.manager? %>
        <th>Manager actions</th>
      <% else %>
        <th>Actions</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @issuances.each do |issuance|%>
      <tr>
        <% if issuance.issuable_type == 'Equipment'%>
          <td><%= issuance.user.full_name.capitalize %></td>
          <td><%= issuance.issuable_type %></td>
          <td><%= issuance.issuable&.name&.capitalize %></td>
          <td><%= issuance.issuable.description %></td>
          <td><%= issuance.issuable.kind.capitalize %></td>
          <td><%= issuance.created_at.strftime("%D") %></td>
          <td><%= issuance&.issuer&.full_name %></td>
          <td><%= issuance.state %></td>
          <% if (issuance.user != current_user) && current_user.manager? %>
            <td>
              <%= form_for issuance do |f|%>
                <% if issuance.approved? %>
                  <%= f.submit "Reject" , class: "button tiny alert round" %>
                <% elsif issuance.rejected?%>
                  <%= f.submit "Approve", class: "button tiny success round" %>
                <% else %>
                  <%= f.submit "Approve", class: "button tiny success round" %>
                  <%= f.submit "Reject" , class: "button tiny alert round" %>
                <% end %>
              <% end %>
            </td>
          <% else %>
            <td><%= link_to "View", issuance_path(issuance) , class: "button tiny success round"%>
              <%= link_to "Edit", edit_issuance_path(issuance), class: "button tiny notice round" %>
             <%= link_to "Revoke", issuance_path(issuance), method: :delete, class: "button tiny alert round" %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/issuances/edit.html.erb
<% provide(:title,"Edit Issuance") %>
	<%= render 'form' %>

app/views/issuances/index.html.erb
<% provide(:title, "Leaves") %>
<div class="panel" align="center">
  <% if @leaves.any? %>
    <hr>
    <h3> Leave Requests </h3>
    <hr>
    <br>
    <%= render 'leaves/leave' %>
    <hr>
  <% end %>

  <% if @issuances.map(&:issuable_type).include?('Equipment') %>
    <h3> Equipment Requests </h3>
    <hr>
    <br>
    <%= render 'issuances/issuance_equipment' %>
    <hr>
  <% end %>

  <% if @issuances.map(&:issuable_type).include?('Access') %>
    <h3> Access Requests </h3>
    <hr>
    <br>
  	<%= render 'issuances/issuance_access' %>
  <% end %>
  <hr>
  <h3> Leave Calender </h3>
  <%= month_calendar events: Leave.all do |date, leaves| %>
    <%= date %>

    <% leaves.each  do |leave| %>
      <div>
  	    <% if leave.state == 'approved'  %>
  	       <b>On Leave</b> (<%= leave.user.first_name.capitalize %>)
  	    <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/issuances/new.html.erb
<% provide(:title,"New Equipment") %>
	<%= render 'form' %>

app/views/issuances/show.html.erb
<% provide(:title,"Issuances")%>
<div class="panel" align = "center">
  <h1>Issuance Request</h1>
  <table>
    <thead>
      <tr>
        <th>Employee Name</th>
        <th>Request for</th>
        <% if @issuance.issuable_type == 'Access' %>
          <th>Access Name</th>
          <th>Access URL</th>
          <th>Access Type</th>
        <% else %>
          <th>Equipment Name</th>
          <th>Equipment Requested for</th>
          <th>Type</th>
        <% end %>
        <th>Requested On</th>
        <th>Manager's Name</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @issuance.user.full_name.capitalize %></td>
        <td><%= @issuance.issuable_type %></td>
        <% if @issuance.issuable_type == 'Access' %>
          <td><%= @access.name.capitalize %></td>
          <td><%= @access.url %></td>
          <td><%= @access.kind.capitalize %></td>
        <% else %>
          <td><%= @equipment.name %></td>
          <td><%= @equipment.description %></td>
          <td><%= @equipment.kind %></td>
        <% end %>
        <td><%= @issuance.created_at.strftime("%D") %></td>
        <td><%= @issuance&.issuer&.full_name %></td>
        <td><%= @issuance.state %></td>
      </tbody>
    </table>
</div>