config/routes.rb
Rails.application.routes.draw do
  resources :equipment
  resources :issuances
  resources :accesses
  resources :attendances
  resources :leaves
  root 'attendances#index'

  resources :equipment do
    resources :issuances
  end

  resources :accesses do
    resources :issuances
  end

  devise_for :users, :controllers => { registrations: 'registrations' } do
    member do
      get :managers, :employees
    end
  end

  resources :products, only: [:index]
  # resources :roles,  only: [:create, :destroy]
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= foundation_flash_class(key) %> alert-box">
    <%= value %>
    <a class="close" href="#">&times;</a>
  </div>
<% end %>

app/views/layouts/_head.html.erb
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>SmarterHR | <%= content_for?(:title) ? yield(:title) : "" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

app/views/layouts/_header.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="/">SmarterHR</a></h1>
    </li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <%if user_signed_in? %>
          <li class="has-dropdown equipment">
            <a href="#">Requests </a>
            <ul class="dropdown">
              <li><%= link_to  "My Requests", issuances_path if current_user.employee? %></li>
              <li><%= link_to "Employee requests", issuances_path(manager: true) if current_user.manager?%></li>
            </ul>
          </li>
        <li>
      </li>
       <li class="has-dropdown profile">
        <a href="#"> <%= current_user.full_name.capitalize %> </a>
        <ul class="dropdown">
          <li> <%= link_to "Profile",edit_user_registration_path %></li>
          <li> <%= link_to "SignOut",destroy_user_session_path, method: :delete%></li>
        </ul>
       </li>
      <% end %>
    </ul>
    <!-- Left Nav Section -->
      <% if user_signed_in? %>
        <ul class="left">
          <% if current_user&.super_manager? %>
            <li><%= link_to "New Equipment", new_equipment_path %> </li>
          <% else %>
          <li class="has-dropdown request">
            <a href="#"> New Request </a>
            <ul class="dropdown">
              <li><%= link_to "Access", new_access_path  %></li>
              <li><%= link_to "Leave", new_leave_path  %></li>
              <li><%= link_to "Equipment", new_issuance_path  %></li>
            </ul>
          </li>
          <% end %>
        </ul>
    <% end %>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>